### ISSUE TITLE
Upgrade to Boost 1.70+ (but can not due to Bazel bug)

### ISSUE THREAD

**Issue by terrisgit** [nelhage/rules_boost#119]
This is an awesome project! Thank you!

**Comment by ctrysbita** [comment]
1.71 has been released. Any update on upgrading boost version? @nelhage

**Comment by jsharpe** [comment]
Boost 1.70 hits this bug: https://github.com/bazelbuild/bazel/issues/374. I don't know if there's a workaround for this.

**Comment by nelhage** [comment]
Fixed in #143!

**Comment by terrisgit** [comment]
.. only if you build Bazel from source until Bazel 1.1.1 is released. I built Bazel from source and it indeed works (FYI for anyone who is reading..).

**Comment by nelhage** [comment]
This is working in CI with Bazel 1.1.0 from a release tarball, so I don't _believe_ 1.1.1 to be required

**Comment by terrisgit** [comment]
I had the “bad filename” error with 1.1.0 on OSX.

**Comment by terrisgit** [comment]
It’s in bazel 2.0 ! Woot !
