### ISSUE TITLE
Test on Bazel CI

### ISSUE THREAD

**Issue by laurentlb** [nelhage/rules_boost#128]
Hi,

It looks like `rules_boost` is useful to many Bazel users and would benefit from being tested on Bazel CI (to ensure Bazel releases don't break it).

https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md

**Comment by drigz** [comment]
Can this be closed now? Presubmits appear to be enabled: https://buildkite.com/bazel/rules-boost

**Comment by nelhage** [comment]
I'm going to close this out since I think we're done on our side. @laurentlb if there's anything else we need to do, please just let us know over email or via a new issue.
