### ISSUE TITLE
Enable Windows build on Bazel CI

### ISSUE THREAD

**Issue by drigz** [nelhage/rules_boost#133]
#132 enabled Bazel CI, but disabled the Windows build. Example failure: https://buildkite.com/bazel/rules-boost/builds/4#9c49faea-f22c-4b6b-b92d-bee0c4c088dd

There are various different errors with various libraries, so this will require quite wide-ranging changes.

**Comment by drigz** [comment]
I have been experimenting on https://github.com/nelhage/rules_boost/tree/fix-windows-ci, where I've made quite good progress, but ran into a segfault in `:beast_test` that I'm not sure how to debug.

**Comment by nelhage** [comment]
Resolved by #134
