### ISSUE TITLE
test target link failure

### ISSUE THREAD

**Issue by forest-rouse** [nelhage/rules_boost#139]
I am trying to build a open source project colmap suing Bazel.  I am using the boost test dependency in  deps = ["@boost//:test"]

`cc_test(
    name = "bitmap_test",
    size = "small",
    srcs = ["src/util/bitmap_test.cc"],
    linkstatic = 1,
    deps = [
        ":lib",
        "@boost//:test",
    ],
)`

but there are link errors for missing symbols in the boost::unit_test namespace.  For instance

> ld.lld: error: undefined symbol: boost::unit_test::unit_test_log_t::set_checkpoint(boost::unit_test::basic_cstring<char const>, unsigned long, boost::unit_test::basic_cstring<char const>)
>>> referenced by bitmap_test.cc
>>>               bazel-out/k8-opt/bin/third_party/colmap/_objs/bitmap_test/bitmap_test.o:(TestBitmapGrayColor_invoker())

I looked at the missing symbols and they all corresponded to *.ipp files and noticed that cpp files were in libs/test/src/.  The test target excludes these files.

`boost_library(
    name = "test",
    exclude_src = glob(["libs/test/src/*.cpp"]),
    deps = [
        ":algorithm",
        ":assert",
        ":bind",
        ":call_traits",
        ":config",
        ":core",
        ":current_function",
        ":detail",
        ":exception",
        ":function",
        ":io",
        ":iterator",
        ":limits",
        ":mpl",
        ":numeric_conversion",
        ":optional",
        ":preprocessor",
        ":smart_ptr",
        ":static_assert",
        ":timer",
        ":type",
        ":type_traits",
        ":utility",
        ":version",
    ],
)
`
I commented the **exclude_src** line and the link errors were eliminated.

**Comment by forest-rouse** [comment]
I see the #92 had the same problem.  Tried the solution there and it worked.  It may be that we are using an old version of boost_rules.  I'm going to check the commit numbers.

**Comment by reltuk** [comment]
We introduced `@boost//:test.a` and `@boost//:test.so` in #147 to meet the non-included unit_test_framework use case. Please switch to those targets, and feel free to reopen this issue or file a new one if you see any further problems. Thank you!
