### ISSUE TITLE
error downloading tarsal

### ISSUE THREAD

**Issue by apcode** [nelhage/rules_boost#15]
I'm seeing this error when trying to use the boost dep, any ideas?

Error downloading [https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download] to /home/alan/.cache/bazel/_bazel_alan/50d2d8587c8bcf0c3c09e1faf2188140/external/boost/download.tar.bz2: Received fatal alert: handshake_failure and referenced by '//examples:boost'

**Comment by apcode** [comment]
s/tarsal/tarball/ in the title :)

**Comment by nelhage** [comment]
Try using a newer revision of this repo -- e.g. `d6446dc9de6e43b039af07482a9361bdc6da5237` is the current master. We've moved to pulling the tarball from a more reliable mirror. I'll update the README.
