### ISSUE TITLE
Build fail on ppc64

### ISSUE THREAD

**Issue by alanpeixinho** [nelhage/rules_boost#150]
Please add an option to build, or maybe an empty condition in order not to fail on non supported platforms.

Thanks

**Comment by reltuk** [comment]
Thanks for the report! We would love to fix this. I tried to get an emulator up so I could test changes, but I ran overtime of a time box. I don't have a quick way to iterate here in the short term. This make take a bit for us to get around to, but we're very open to PRs in this space.

**Comment by nelhage** [comment]
This is fixed by #156. Feel free to open a new issue if something still doesn't work for you.
