### ISSUE TITLE
Problem compiling boost with current master branch

### ISSUE THREAD

**Issue by awhillas** [nelhage/rules_boost#16]
Hey,
I have been getting errors trying to get this to compile. I have deviated from the README.md slightly (as it was well out of date!) and have this in my WORKSPACE file:
```python
http_archive(
    name = "com_github_nelhage_boost",
    strip_prefix = "rules_boost-master",
    type = "tar.gz",
    urls = [
        "https://github.com/nelhage/rules_boost/archive/master.tar.gz"
    ],
)
load("@com_github_nelhage_boost//:boost/boost.bzl", "boost_deps")
boost_deps()
```
but i'm getting this when trying to use `@boost//:test` as a `deps`:
```
ERROR: /private/var/tmp/_bazel_alex/2d57536a86fcea3046c07ff4838acca7/external/boost/BUILD.bazel:581:1: Linking of rule '@boost//:test' failed (Exit 1).
duplicate symbol _main in:
    bazel-out/local-fastbuild/bin/external/boost/_objs/test/external/boost/libs/test/src/cpp_main.pic.o
    bazel-out/local-fastbuild/bin/external/boost/_objs/test/external/boost/libs/test/src/unit_test_main.pic.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Not sure where to go with this. I'd looooove to get Boost working with Bazel but i'm a nube to both Bazel and C++. Anyone get this working recently?

**Comment by nelhage** [comment]
Can you give it a try with commit b24d942a5b74eaa00d44f159c2bfcaa07b4ae62d ? That works in my testing. I'll merge it if so (and hopefully add a circleci build)

**Comment by reltuk** [comment]
This is fixed now, so I'll go ahead and close this. Please feel free to reopen if you need anything further here.
