### ISSUE TITLE
Building on Android by removing -lpthread

### ISSUE THREAD

**Issue by cpsauer** [nelhage/rules_boost#165]
Thank you, @nelhage, for an amazingly helpful set of rules!

I'm writing to ask if you'd consider updating the rules so they could be built on Android (NDK). The only issue I'm seeing is that pthread isn't a separate library from libc on Android, so linking (w/ -lpthread) fails. 

If we select out -lpthread on Android, I think that would do the trick. Protobuf/tensorflow dealt with a similar issue [here](https://github.com/protocolbuffers/protobuf/pull/1386). (However, I'm not sure their solution actually selects for the right thing in the current version of Bazel; the select doesn't seem to match, using the [minimal NDK example from the bazel page](https://docs.bazel.build/versions/2.0.0/android-ndk.html) as a test. This is all a bit of a mess pre Bazel platforms shipping--but I thought you might know better than I how to select robustly for Android. Since the {"crosstool_top": "//external:android/crosstool"} doesn't seem to work robustly, internally we're selecting on {"android_crosstool_top": "@androidndk//:default_crosstool"}, which is an alias of the default, and then pass it in with `bazel build --android_crosstool_top=@androidndk//:default_crosstool ...` when we're building for Android.)

-Chris

P.S. I just read a bit of your blog, and it put a big smile on my face :)

**Comment by nelhage** [comment]
I'd happily apply a patch. I'm afraid I don't have any particular expertise working with Android and Bazel, so I can't suggest a better solution. If you can find something that works and seems likely to help others, though, I'd accept a PR!

**Comment by cpsauer** [comment]
Hi @nelhag. The best solution for us turned out to be making the android NDK behave more like other linux-based platforms with a dummy pthread library. That way we could just use libraries (like this one) on Android without modification, and it avoids the current issues around the half-released Bazel platforms. I think that's the best solution until Bazel fixes those issues or adds something that makes the NDK behave more like other platforms.

**Comment by nelhage** [comment]
Thanks for the update! I'm going to close this, but feel free to open a new issue or PR if there's eventually a better solution!
