### ISSUE TITLE
Use BOOST_ASIO_SEPARATE_COMPILATION for Boost.Asio

### ISSUE THREAD

**Issue by mehrdadn** [nelhage/rules_boost#166]
Hi, I just wanted to suggest using `BOOST_ASIO_SEPARATE_COMPILATION` for Boost.Asio.

Most other heavyweight Boost libraries already require separate compilation, but Asio has left its default as header-only for convenience (so users don't have to deal with the complexity of compiling and linking to Boost). But given Bazel already takes care of that complexity, it seems better to compile the library separately and link to it.

To do this, you can just [follow the instructions here](https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/using.html#boost_asio.using.optional_separate_compilation), e.g.:

	boost_library(
	    name = "asio",
	    srcs = [
	        "boost/asio/impl/src.cpp",
	        "boost/asio/impl/src.hpp",
	    ],
	    defines = [
	        "BOOST_ASIO_SEPARATE_COMPILATION",
	    ] + select({
	    ...

(Also see the note about `#include <boost/asio/ssl/impl/src.hpp>` for SSL use. I'm not sure if that's best included in the same target or a separate one, if any.)

Thanks!

**Comment by nelhage** [comment]
This makes sense to me! Would you be up for sending a pull request implementing this change?

**Comment by mehrdadn** [comment]
Would you be fine if I didn't put my full name and email in the git repo? (Sorry, just prefer not to have my name in many repos.) If so then I'm happy to.

In which case, please let me know what you'd prefer me to do about the SSL header. I can e.g. add a `.cpp` file that does `#include <boost/asio/ssl/impl/src.hpp>` or add patch to include it in `src.cpp`, I can make a separate `asio_ssl` target or include it in `asio`, etc.

**Comment by nelhage** [comment]
Yeah, please feel free to send a PR under a pseudonym! As I expect you're aware, GitHub makes available `<username>@users.noreply.github.com` for this purpose if you don't have another option you'd prefer: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#about-commit-email-addresses

I think I'd suggest leaving out the SSL include; users can add that themselves, and add a dependency on whatever OpenSSL implementation they want. It's pretty common for bazel projects to pull in BoringSSL from source, and it'd be nice to give downstreams full control.

**Comment by mehrdadn** [comment]
Okay sounds good, thanks!
