### ISSUE TITLE
BOOST_ASIO_SEPARATE_COMPILATION breaks asio ssl engine include

### ISSUE THREAD

**Issue by nickolasrossi** [nelhage/rules_boost#178]
PR #167 introduced BOOST_ASIO_SEPARATE_COMPILATION, but this results in boost/asio/ssl/detail/impl/engine.ipp failing to be included in compilation (because BOOST_ASIO_HEADER_ONLY is now not defined), and thus the linker can't find any symbols from ssl engine, e.g.:

ld.lld: error: undefined symbol: boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)
ld.lld: error: undefined symbol: boost::asio::ssl::detail::engine::native_handle()
ld.lld: error: undefined symbol: boost::asio::ssl::context::~context()
...

So far I don't have a solution other than reverting to the commit prior to PR #167.

**Comment by nelhage** [comment]
Do you have a minimal test program that demonstrates the problem? I can take a look and try to find a better solution if so.

**Comment by scm-ns** [comment]
Hahha. I have been scratching my head so much trying to figure this out. I add the same errors.

**Comment by nickolasrossi** [comment]
Sorry for the late reply -

I don't have a clang command line for this, but the beast ssl examples should exhibit the issue:

https://www.boost.org/doc/libs/1_71_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp

**Comment by scm-ns** [comment]
Using commit `353a58c5d231293795e7b63c2c21467922153add` ( The one just before the PR #167 ) in the WORKSPACE prevents the asio error.

**Comment by nelhage** [comment]
I just pushed #179, which should make ASIO SSL available via `@boost//:asio_ssl`. I made it a separate target to avoid depending on OpenSSL unnecessarily.

Can someone implicated by this try out that branch and report if this works for you? I pulled in a test case that demonstrates that it links properly, but I haven't actually tried it out.

**Comment by nickolasrossi** [comment]
Compiles for me now.
