### ISSUE TITLE
Open to suppressing all warnings?

### ISSUE THREAD

**Issue by TheButlah** [nelhage/rules_boost#184]
I've submitted a number of PRs suppressing or fixing warnings on macos, but every few weeks I find new warnings. Instead of continually submitting new PRs to suppress these warnings, would you be open to just universally providing `-w` to suppress all warnings?

**Comment by nelhage** [comment]
Yeah, I'd likely take that PR; I'm not sure it's doing us any good to show warnings in Boost code.
