### ISSUE TITLE
undefined symbol: _ZN5boost6detail12set_tss_dataEPKvPFvPFvPFvES3_ES5_S3_b

### ISSUE THREAD

**Issue by edsky** [nelhage/rules_boost#188]
```
cc_library(
    name = "ww",
    srcs = ["common/loader.cc", "ww.cc"],
    hdrs = glob(["common/*.h"]),
    deps = [
        "@boost//:thread",
    ],
)
```

Can be compiled successfully, but failed to load so, the display is as in the title.
Use `boost::thread_specific_ptr`

**Comment by nelhage** [comment]
I am unable to reproduce; [a short test case](https://github.com/nelhage/rules_boost/commit/thread-specific-ptr) works fine. Are you able to provide a workspace that reproduces the problem?

**Comment by ChrisCummins** [comment]
@edsky are you building on a mac? I have run into load-time errors like yours before when boost is installed via homebrew, the solution was to `brew uninstall boost`.

Cheers,
Chris

**Comment by cpsauer** [comment]
I'm going to close this one down as v old and not reproducing, but if someone runs into it again, holler, and I'll open things right back up.
