### ISSUE TITLE
Mac M1 Compatiblity

### ISSUE THREAD

**Issue by deetungsten** [nelhage/rules_boost#211]
Hello,

I came across this issue ticket/bug [#7184](https://github.com/ray-project/ray/issues/7184) and I am having the same issue but with the new Apple Silcon/M1. I was wondering if anyone has any insight on how to solve this? Boost and bazel are both natively compatible but I cannot seem to figure out where to point the conditions to. 

Thank you!

**Comment by nelhage** [comment]
#208 added support for M1 macs, and it works on `master` on my M1 Air. Are you still having troubles with the latest commit?

**Comment by jv33ck** [comment]
@nelhage when you say it works on master do you mean you were able to install using pip? I have an M1 MBP and have not been able to get ray installed. So far I have tried pip install, conda install, and just tried building from source with no luck after hours of researching the problem. Granted I am still in the early stages as far as experience goes.
