### ISSUE TITLE
dependency repo org_lzma_lzma download error

### ISSUE THREAD

**Issue by xiedeacc** [nelhage/rules_boost#256]
WARNING: Download from https://phoenixnap.dl.sourceforge.net/project/lzmautils/xz-5.2.3.tar.gz failed: class java.io.IOException Read timed out

**Comment by Vertexwahn** [comment]
I frequently observe the same issue:
![image](https://user-images.githubusercontent.com/3775001/180087168-af3a49a4-907a-4db4-b5e1-da039e6f9cd7.png)
