### ISSUE TITLE
http_archive in README is 1.76 not 1.80, How to use latest boost? 

### ISSUE THREAD

**Issue by liushiqi9** [nelhage/rules_boost#261]
`http_archive(
    name = "com_github_nelhage_rules_boost",
    sha256 = "c1b8b2adc3b4201683cf94dda7eef3fc0f4f4c0ea5caa3ed3feffe07e1fb5b15",
    strip_prefix = "rules_boost-%s" % _RULES_BOOST_COMMIT,
    urls = [
        "https://github.com/nelhage/rules_boost/archive/%s.tar.gz" % _RULES_BOOST_COMMIT,
    ],
)`
Will download 1.76 version of boost, which won't compile on gcc 12.2 with c++20. 
And I see commit with message "Bump to 1.80.0". How can I use it?

**Comment by jessberg** [comment]
I have this same issue. Have you figured it out?

**Comment by jessberg** [comment]
I found this worked for me.
```
_RULES_BOOST_COMMIT = "630cf5dbad418ee8cfa637b1e33125b11807721d"                
                                                                                
http_archive(                                                                   
    name = "com_github_nelhage_rules_boost",                                    
    sha256 = "8be3ad3578231579f3d289c0330fd90975fe437451830a569a9a35661104a211",
    strip_prefix = "rules_boost-%s" % _RULES_BOOST_COMMIT,                      
    urls = [                                                                    
        "https://github.com/nelhage/rules_boost/archive/%s.tar.gz" % _RULES_BOOST_COMMIT,
    ],                                                                          
)                                                                             
                                                                                
load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")         
boost_deps() 
```

**Comment by cpsauer** [comment]
Seems like this is just a matter of people not realizing that the README hash is out of date (since it's a pain to update). Right guys?

@nelhage, would you be down with me copying over the language I use in my bazel open source repos to encourage people to grab the latest? Maybe also with encouragement to use Renovate so people stay up to date by default?

**Comment by nelhage** [comment]
@cpsauer That sounds great. Definitely worth a try to see if we can reduce confusion here.

**Comment by cpsauer** [comment]
PR landing shortly, fixing this by adding instructions on how to stay up to date!

Also, hello again @liushiqi9! I'm pretty sure we've interacted over at https://github.com/hedronvision/bazel-compile-commands-extractor
