### ISSUE TITLE
Splitting out zlib for reuse

### ISSUE THREAD

**Issue by cpsauer** [nelhage/rules_boost#274]
Hey @nelhage,

Any chance you'd be open to splitting out, e.g., zlib as a reusable dependency? I was spinning up some code to make it easy for people to make https requests from C++ from Bazel (https://github.com/hedronvision/bazel-make-cc-https-easy), and it'd be great to reuse.

Thanks for all you do!
Chris

**Comment by nelhage** [comment]
You're welcome to copy any of our `BUILD.*` files into your project or into an external project; I'm not sure it makes sense for this project to expose them individually as part of our API surface area.

**Comment by cpsauer** [comment]
I was hoping we could keep collaborating on it, rather than copying and fragmenting, especially since I've [contributed some goodies to it](https://github.com/nelhage/rules_boost/commits/master/BUILD.zlib) in the past.

One good way to do that but to not add it to your surface area would be to split it out into a separate repo, which we both depend on and which others could use? It feels like such an essential component that there should be an easy way to use it from Bazel. But I figured I should reach out to you first before doing that--and I'm realizing I don't need it as urgently as I originally thought.

**Comment by cpsauer** [comment]
(Another good place we might be able to collaborate is on platform_mappings, since they're required for Apple and Android rules users to make use of this library. Haven't open sourced our work there yet, but may well soon. Tracking over at https://github.com/hedronvision/bazel-make-cc-https-easy/issues/4)

**Comment by nelhage** [comment]
Yeah, I see the merits of having it (and maybe some of the other compression libraries) in a shared place that many projects can use.

I'm hesitant to take them on as API surface area in part because I personally am not working with Bazel much these days and don't have a ton of time to do maintenance on this repository or other Bazel projects, so I don't want to take on additional responsibilities as best I can.

Splitting out into another repository might be an option. As another angle, I wonder if you are using rules_boost / bazel more actively and would be interested in a commit bit on the repository and helping out with PR review / maintenance :)

**Comment by cpsauer** [comment]
Totally get it. My mental model was that it'd be about equal maintenance since the compression libs are already depended on, but I get the *already enough Bazel on my plate* feeling.

I'd be honored to get a commit bit and promise to be worthy of that trust. I probably shouldn't take on too much general maintenance, since I have a couple other Bazel tools open sourced (including this new one) and need to focus mostly on the company I'm starting. But I'd be happy to just do things where I see a good fix--and thus either eliminate the review burden for my PRs, or shift it to be asynchronous, with you just pinging me to fix anything I added that you don't like. Also totally happy to always run things by you first! You tell me which of those appeals most.

One additional example that springs to mind is updating boringssl (the one current PR). For that, I'd propose I automate the update process with Renovate and then eliminate that category of maintenance while getting all the latest security patches. I just did that for the repo I spun up (and linked up top), including making an auto updating mirror of the boringssl-with-bazel branch of openssl to enable Renovate to auto track the latest. Happy to duplicate the config over here. If you want that, just add the Renovate GitHub app to the repo (which I think requires you to do, only a few clicks) and I'll take care of the rest. (I'm already engaged with the Renovate team on removing the necessity of the auto tracking repo, with the boringssl folks on improving windows/android support by enabling assembly implementation for those platforms, and with the Bazel platforms folks on reducing some of the Apple platforms selection verboseness, though that's moving slowly.)

On the original question that spawned this issue, I propose the following: Let's table making the compression libraries reusable until this new project actually needs it. And then when that happens, I'll spin up a new repo and point us both at it, happily giving you commit access, too, assuming you want it, and making both of us auto-track it with Renovate, eliminating additional maintenance burden.

**Comment by nelhage** [comment]
I'm happy to give you a commit bit on the basis of your contributions and apparent interest in improving the project, and skimming your bio and other contributions!

The main maintenance burden historically on this repository has just been handling inbound PRs; we're fortunate to have a pretty involved set of users who are proactive about submitting fixes. So even if you just have time to  merge a few PRs that seem like they're fixes/improvements/cleanups, that'd be awesome :)

I'm also happy for you to self-review PRs if you feel confident they aren't controversial or major changes. I'll keep an eye asynchronously as things land.

Setting up Renovate to track boringssl would be lovely -- I've felt vaguely irresponsible carrying out-of-date pins of such a security critical dependency.

The proposal for the compression libraries sounds great to me.

Thanks so much for the understanding and the contributions!

**Comment by cpsauer** [comment]
Accepted! I'm honored--and certainly excited to help make things better as I see good opportunities. A great community, indeed :) Thanks so much for all the wonderful things you do here!

I'll start by pushing up a fix to #261, as we'd discussed, thinking I already have your buy in and that like me to just do my best to minimize confusion there without having it bother you further. (And that you've (maybe) seen the language I'd proposed copying in my other (linked) repos anyway.) More details in the commit message if you want em :) If that's not the action you'd like--or you'd like something else--please tell me and/or overwrite. I'm super coachable and am learning what you'd like.

Since we're tabling the compression library breakout, I'll close this issue for now. But, I might occasionally reply here as "collaborator chat", tagging you, when I don't need to bug other people but have a question. If you'd rather we do that another way (e.g. email) just say. As above, I'm coachable--and trying to guess at good defaults in the meantime.

One other thing I'd like to add to the README/setup if you're cool with it, copied over from another repo of mine: If people are trying to use this from the the Apple or Android-specific rules, they'll need to set up `platform_mappings`, until Bazel resolves its outstanding issues. These make the OS select()s work properly with the transitions in the implementations of those rules. It's not hard if you know what to to do, but can be tricky to figure out, and AFAIK, there aren't any working examples in their docs except ones I've commented to help people on issues. I don't have a public repo with instructions just yet--though I do have a working setup. What I'd like to do as a stopgap is to point people who want help over to a tracking issue (in that other repo), and, if there's demand, I'll spin up another repo we can both point to with instructions. In any event, it's worth giving people a heads up because otherwise they're likely to stumble into all sorts of hard-to-debug issues and report them.

Anyway, I'll tackle the Renovate stuff next! It may be a little incremental. Thanks for enabling :)

Cheers!
Chris
