### ISSUE TITLE
Could you add the safe_numerics module?

### ISSUE THREAD

**Issue by sarahec** [nelhage/rules_boost#323]
I discovered that safe_numerics isn't included. Thank you.

**Comment by cpsauer** [comment]
Hey, Sarah! This is, for better or worse, a bit more of a self-service, community effort.
Would you be willing to give adding safe_numerics a go?

**Comment by cpsauer** [comment]
Yay! Thanks for contributing, Sarah, making this better for everyone.

If you've got a short usage snippet, would you be down to contribute it to the test subdirectory, parallel to the others? That'll help make sure, among other things, that it's dependencies get updated correctly into the future.

Thanks again!
Chris
