### ISSUE TITLE
Log2 library within boost

### ISSUE THREAD

**Issue by trivigy** [nelhage/rules_boost#33]
Any advice on how to import the logging library?

**Comment by nelhage** [comment]
I don't have a target for it, so someone would need to add one and submit a PR, which would look somewhat similar to https://github.com/nelhage/rules_boost/pull/34

You can figure out the list of dependencies generally via trial-and-error and/or `grep`ing the library.

I'm traveling this weekend but may have time to do it myself sometime this week if you can't get to it.
