### ISSUE TITLE
Missing `<boost/version.hpp>`

### ISSUE THREAD

**Issue by lalten** [nelhage/rules_boost#435]
It would be great to generate this header. It is present for regular system installations.

My local copy currently contains
```c++
(...)
//
//  Caution: this is the only Boost header that is guaranteed
//  to change with every Boost release. Including this header
//  will cause a recompile every time a new Boost version is
//  used.
//
//  BOOST_VERSION % 100 is the patch level
//  BOOST_VERSION / 100 % 1000 is the minor version
//  BOOST_VERSION / 100000 is the major version

#define BOOST_VERSION 107400

//
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
//  but as a *string* in the form "x_y[_z]" where x is the major version
//  number, y is the minor version number, and z is the patch level if not 0.
//  This is used by <config/auto_link.hpp> to select which library version to link to.

#define BOOST_LIB_VERSION "1_74"
```

I'm not really sure where the version.hpp is generated during an install but it seems easy enough to make a genrule based on `boost/Jamfile`:
https://github.com/boostorg/boost/blob/b6928ae5c92e21a04bbe17a558e6e066dbe632f6/Jamroot#L147
```
constant BOOST_VERSION : 1.82.0 ;
```

**Comment by lalten** [comment]
On second glance it turns out the file lives in `external/boost/libs/config/include/boost/version.hpp`.
Depending on `@boost//:config` instead of `@boost//:version` does make it available (instead of `/usr/include/boost/version.hpp` leaking in)
Is this expected behavior?

**Comment by lalten** [comment]
What is the purpose of `@boost//:version` anyways? It does not contain any source files:

```sh
❯ bazel query @boost//:version --output build
```
```
cc_library(
  name = "version",
  visibility = ["//visibility:public"],
  generator_name = "version",
  generator_function = "boost_library",
  generator_location = "(...)/external/boost/BUILD.bazel:2226:14",
  srcs = [],
  hdrs = [],
  includes = ["libs/version/include"],
  defines = select({"@boost//:windows_x86_64": ["BOOST_ALL_NO_LIB"], "//conditions:default": []}) + [],
  copts = select({"@platforms//os:windows": [], "//conditions:default": ["-Wno-unused"]}) + [],
  licenses = ["notice"],
)
```

**Comment by cpsauer** [comment]
Predates me, so I don't know the history, but seems like we should cut :version, since it's empty, subsumed by config, and causes confusion.

Would you be down to toss up a quick PR, @nelhage to approve with his greater context?
