### ISSUE TITLE
Clarification Needed: sha256 Requirement in http_archive for Renovate

### ISSUE THREAD

**Issue by hans-brgs** [nelhage/rules_boost#475]
Dear nelhage,

I have started to integrate Renovate with the use of your repository and faced difficulties due to the lack of a clear requirement for the `sha256` attribute in `http_archive`. Without it, Renovate couldn't detect the dependency, leading to confusion.

**Suggestion:** Can you update the comments in the documentation above, to explicitly state that the `sha256` attribute must be included in `http_archive` when using Renovate?

This clarification would save developers time and effort  (like me, who lost two days figuring this out! 🥲).

Thank you,
Hans

https://github.com/nelhage/rules_boost/blob/b06800149136b5f955311a1ff0cc1919b3e2e3db/README.md?plain=1#L12-L20

**Comment by cpsauer** [comment]
oops, that's on me. Thanks for reporting. (It didn't use to be required, I don't think, and probably shouldn't be, given it's not required by bazel. Maybe got added in their last Bazel refactor.)

Happy to add to the instructions, but I really think we should probably instead be getting them to make sha256 optional. Any chance you'd be willing to file it with them, linking back here?

**Comment by hans-brgs** [comment]
Absolutely! I've begun a discussion with the Renovate team on GitHub about this feature. The conversation can be followed and contributed to [here](https://github.com/renovatebot/renovate/discussions/23692). 

I also wanted to thank you for your work on rules_boost!

**Comment by cpsauer** [comment]
Thanks so much for doing and for being great. I'll drop in a quick 2c backing you up. Again, really appreciate your being the type of person who looks to make things better for the folks who come after you.

Would you prefer keep this open--or shall we close, figuring that the right move is to have Renovate fix (and reopening if they don't)?

**Comment by hans-brgs** [comment]
I agree with closing this issue and allowing the Renovate team to work on it. In the meantime, here's a final summary for anyone who encounters the same problem in the future.

## Summary of the Situation:
The error encountered was that Renovate was not detecting the Boost dependency if `sha256` was not explicitly added to `http_archive`. While we await Renovate's update to make `sha256` optional, users can follow the steps below as a workaround:

In your `http_archive` in `WORKSPACE` file:

```
http_archive(
    name = "com_github_nelhage_rules_boost",
    url = "https://github.com/nelhage/rules_boost/archive/96e9b631f104b43a53c21c87b01ac538ad6f3b48.tar.gz",
    strip_prefix = "rules_boost-96e9b631f104b43a53c21c87b01ac538ad6f3b48",
)
```
Add `sha256 =` with the latest commit hash. You can find the latest commit hash [here](https://github.com/nelhage/rules_boost/commits/master).

For more information and context, please follow the links below:
- [Renovate Bazel Documentation](https://docs.renovatebot.com/bazel/#http_archive-and-http_file)
- [Renovate GitHub Discussion](https://github.com/renovatebot/renovate/discussions/23692#discussioncomment-6628504)

Thanks again for all your work!

Please feel free to refer to this issue if needed in the future.
