### ISSUE TITLE
Illegal ambiguous match on configurable attribute "srcs"  in `@com_github_facebook_zstd//:zstd` on Windows

### ISSUE THREAD

**Issue by rjhuijsman** [nelhage/rules_boost#535]
When importing any version of `rules_boost` at or beyond PR https://github.com/nelhage/rules_boost/pull/319, Bazel `5.4.1` will fail when running on an x86 Windows machine:

```
ERROR: C:/users/runneradmin/_bazel_runneradmin/ph3foyed/external/com_github_facebook_zstd/BUILD.bazel:1:11: Illegal ambiguous match on configurable attribute "srcs" in @com_github_facebook_zstd//:zstd:
@platforms//cpu:x86_64
@com_github_facebook_zstd//:windows_x86_64
Multiple matches are not allowed unless one is unambiguously more specialized.
```

This error is referring to [this `select`](https://github.com/nelhage/rules_boost/blob/e2b3a6894ded11b4dc029c4f23a3eab75ccb5c70/zstd.BUILD#L16).

This happens, for example, with a repo definition like this:
```
maybe(
    git_repository,
    name = "com_github_nelhage_rules_boost",
    commit = "e2b3a6894ded11b4dc029c4f23a3eab75ccb5c70",
    remote = "https://github.com/nelhage/rules_boost",
    shallow_since = "1704518793 +0000",
)
```

I'm unsure (and unfortunately, due to our setup, have been unable to test) whether this issue appears with newer Bazel versions also. I'm aware Bazel 5 is on the older side, but it's [still supported](https://bazel.build/release#support-matrix) and will continue to be for another year. We're, unfortunately, still dependent on it.

Would it be possible to tweak that `select` to have an unambiguous match for all platforms?

**Comment by nelhage** [comment]
Hm, I think this may be the issue that @cpsauer reported in https://github.com/bazelbuild/bazel/issues/14604, which would suggest it's fixed in newer bazel.

I think it should be easy to workaround, though, so I may take a stab.
