### ISSUE TITLE
Integrate with bzlmod

### ISSUE THREAD

**Issue by andrewkatson** [nelhage/rules_boost#546]
According to the newest bazel blog https://blog.bazel.build/2023/12/11/bazel-7-release.html they won't be supporting `WORKSPACE` based dependency management starting with bazel 9 (in bazel 8 it will be disabled by default). So this is just an FYI that if this repo is going to continue to work it needs to be integrated here: https://registry.bazel.build/. 

I love this repo and want to see it continue so thank you for all your great work!

**Comment by Vertexwahn** [comment]
A lot of work is going on already here: https://github.com/bazelbuild/bazel-central-registry/pull/1577
I already use Boost via Bzlmod

**Comment by finn-ball** [comment]
Had a go at this, see my PR above.

**Comment by finn-ball** [comment]
Currently my PR ports this project to bzlmod and is passing CI:
https://github.com/nelhage/rules_boost/pull/553

**Comment by finn-ball** [comment]
With the above PR merged, this is now complete. Please close.
