### ISSUE TITLE
bazel build @boost//:iostream not working

### ISSUE THREAD

**Issue by liberatix-samir** [nelhage/rules_boost#68]
Hello, I am on windows 10, tried with bazel 0.10 and 0.14.

When I add "@boost//:iostreams" to any cc_library I get the error: 
/external/net_zlib_zlib/BUILD.bazel:6:1: in cc_library rule @net_zlib_zlib//:zlib: Expected action_config for 'preprocess-assemble' to be configured. I am not sure if the problem is from the library or If I am doing something wrong, Do you have any what might cause the problem?

Workplace file: 

```
local_repository(
  name = "com_github_nelhage_rules_boost",
  # commit = "239ce40e42ab0e3fe7ce84c2e9303ff8a277c41a",
  # remote = "https://github.com/nelhage/rules_boost",
  path = "third_party/com_github_nelhage_rules_boost",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()
```

and my BUILD file: 
```
cc_library(
    name = "storage",
    srcs = [
      "blobstore.cc",
      "blobstore.h",
    ],
    hdrs = [
      "blobstore.h",
    ],
    deps = [
      "@boost//:iostreams",
    ],
    defines = ["BOOST_ALL_NO_LIB"],
)
```

**Comment by nelhage** [comment]
Wow, I have no idea what's going on there. This error smells like it might be a bazel bug; c.f. https://github.com/bazelbuild/bazel/issues/3505 for a similar error from a year ago or so. I think it might mean Bazel was unable to detect/configure your C/C++ toolchain somehow.

Does building other C++ projects work?

**Comment by liberatix-samir** [comment]
The other projects have no problem unless I add "@boost//:iostreams" dependency to them (9 projects + tests). Also the problem is only in windows, works fine when using linux. Tonight I will try a different windows PC to see if I get the same problem.

**Comment by liberatix-samir** [comment]
Update: The get the errors on Mac and Windows but it compiles and words fine on windows.
bazel build @boost//:iostreams or more specifically build @net_zlib_zlib//:zlib is the cause.

The folder "...external\net_zlib_zlib "is empty but "..external\org_lzma_lzma" and "...external\org_bzip_bzip2" are not.  I thought it is a problem with downloading but with the direct link is working fine. Should not be problem with unziping the files either.

On windows:
 bazel --output_base=C:\BT build @boost//:iostreams
ERROR: C:/bt/external/boost/BUILD.bazel:698:1: no such package '@net_zlib_zlib//': C:/bt/external/net_zlib_zlib (Permission denied) and referenced by '@boost//:iostreams'
ERROR: Analysis of target '@boost//:iostreams' failed; build aborted: no such package '@net_zlib_zlib//': C:/bt/external/net_zlib_zlib (Permission denied)

 bazel build @boost//:iostreams
ERROR: C:/users/samir/_bazel_samir/f3jdn2ka/external/net_zlib_zlib/BUILD.bazel:6:1: in cc_library rule @net_zlib_zlib//:zlib: Expected action_config for 'preprocess-assemble' to be configured
ERROR: Analysis of target '@boost//:iostreams' failed; build aborted: Analysis of target '@net_zlib_zlib//:zlib' failed; build aborted

On Mac:
bazel build @boost//:iostreams
ERROR: /private/var/tmp/_bazel_ace/feccc00fb7c3b07c1f4af822dba815a1/external/boost/BUILD.bazel:691:1: no such package '@net_zlib_zlib//': Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_ace/feccc00fb7c3b07c1f4af822dba815a1/external/net_zlib_zlib/zlib-1.2.11.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '@boost//:iostreams'
ERROR: Analysis of target '@boost//:iostreams' failed; build aborted: no such package '@net_zlib_zlib//': Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_ace/feccc00fb7c3b07c1f4af822dba815a1/external/net_zlib_zlib/zlib-1.2.11.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Elapsed time: 18.149s
FAILED: Build did NOT complete successfully (10 packages loaded)

**Comment by nelhage** [comment]
Hm, your macOS issue looks like it might be unrelated, and possibly related to a firewall or other configuration problem on your end; See e.g.
https://github.com/tensorflow/models/issues/332
and even https://confluence.atlassian.com/adminjiraserver070/connecting-to-ssl-services-779356667.html

**Comment by liberatix-samir** [comment]
Looks like the problem is from bazel. I just got response in stackoverflow
https://stackoverflow.com/questions/50967174/cant-build-a-project-package-using-boost-iostream-from-bazel/51057943#51057943

Thank you, you can close the issue.

**Comment by nelhage** [comment]
Thanks for following up!
