### ISSUE TITLE
Windows:  invalid numeric argument '/Wno-unused-value'

### ISSUE THREAD

**Issue by liberatix-samir** [nelhage/rules_boost#69]
bazel build @boost//:regex gives the error: 

```
ERROR: .../external/boost/BUILD.bazel:806:1: C++ compilation of rule '@boost//:regex' failed (Exit 2)
cl : Command line error D8021 : invalid numeric argument '/Wno-unused-value'
```

It works fine if in boost/boost.bzl we change 
line 21 from 
```
default_copts = ["-Wno-unused-value"]
```
to 
```
default_copts = []
```

**Comment by nelhage** [comment]
Thanks for the report! Can you let me know if commit 25e4da1141c56c207a5692b6d3c2aeeffc656fa4 on https://github.com/nelhage/rules_boost/pull/70 works for you?

**Comment by liberatix-samir** [comment]
It does, thanks!
