### ISSUE TITLE
Problems with building boost/iostreams on windows

### ISSUE THREAD

**Issue by liberatix-samir** [nelhage/rules_boost#71]
Update to: https://github.com/nelhage/rules_boost/issues/68
Here is the issue about the missing action_config: https://github.com/bazelbuild/bazel/issues/5495

Removing "contrib/amd64/amd64-match.S" and "-Wno-implicit-function-declaration" from BUILD.zlib fixed the build issue on windows.
Now the problem I get is from lzma: 
```
ERROR: .../f3jdn2ka/external/org_lzma_lzma/BUILD.bazel:6:1: Executing genrule @org_lzma_lzma//:configure_lzma failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; cd external/org_lzma_lzma && ./configure && cp config.h ../../bazel-out/x64_windows-fastbuild/genfiles/external/org_lzma_lzma/config.h"): The system cannot find the file specified.
```

**Comment by nelhage** [comment]
I'm traveling this week, but going to leave this open to track adopting that zlib fix into our own `BUILD.zlib`.
