### ISSUE TITLE
Mac OS: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz]

### ISSUE THREAD

**Issue by akovachev** [nelhage/rules_boost#75]
This may be specifically a bazel issue. However we have plenty of packages being downloaded in our build and the zlib is the only one it's complaining about.

``wget https://zlib.net/zlib-1.2.11.tar.gz`` works, so I know the file exists.

ERROR: /private/var/tmp/_bazel_***/feccc00fb7c3b07c1f4af822dba815a1/external/boost/BUILD.bazel:496:1: no such package '@net_zlib_zlib//': Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_***/feccc00fb7c3b07c1f4af822dba815a1/external/net_zlib_zlib/zlib-1.2.11.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '@boost//:iostreams'
ERROR: Analysis of target '//***' failed; build aborted: no such package '@net_zlib_zlib//': Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /private/var/tmp/_bazel_***/feccc00fb7c3b07c1f4af822dba815a1/external/net_zlib_zlib/zlib-1.2.11.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by nelhage** [comment]
Oof. I'm willing to take the workaround PR since integrity is indeed ensured by the sha256, but this definitely seems like an upstream bug; Can I ask you to also file on Bazel's issue tracker to make sure they follow up?

**Comment by akovachev** [comment]
I found an issue describing the same problem. And it is more of a java specific, than a bazel specific issue.

https://github.com/bazelbuild/bazel/issues/3915
