### ISSUE TITLE
bazel error: "Error downloading ..."

### ISSUE THREAD

**Issue by alexflint** [nelhage/rules_boost#8]
I am currently getting the following error when depending on `@boost//:system` using these rules:

```
ERROR: /Users/alex/Code/go/src/github.com/zippyai/zippy/packages/MockRobot/BUILD:1:1: 
no such package '@boost//': Error downloading 
[https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download] to 
/private/var/tmp/_bazel_alex/c2b0a41d8882371a0ab2752ce12185be/external/boost/download.tar.bz2: 
Received fatal alert: handshake_failure and referenced by '//packages/MockRobot:MockRobot'.
```

I guess this is a sourceforge issue. I wonder if it's possible to find an alternative place to host these files.

**Comment by nelhage** [comment]
I gave up and dropped the file into an s3 bucket I control with public read ACLs. That should hopefully solve it, and maybe sourceforge will get its act together eventually.
